### ISSUE TITLE
source code not available?

### ISSUE THREAD

**Issue by cesarpachon** [wids-eria/adage_unity_client#2]
hello, having a look at your project, but there is not a single source code file here. where they removed? are they going to be available somewhere? please share what is the status of the project. thanks!

**Comment by markstenerson** [comment]
Hey Cesar,

I'm still working on getting the client code up. There are a couple of
changes that I am looking into for the schema that will allow for more
intuitive visualizations for researchers, developers, and teachers. We are
also in a bit of a transition right now as our server programmer has
started his own indie game projects.

Thanks for the interest :)

-Mark
